apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: dex-operator
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: dex-operator
    app.kubernetes.io/part-of: dex-operator
  name: dex-operator