apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dex-operator
  namespace: dex-operator
  labels:
    app.kubernetes.io/name: dex-operator
    app.kubernetes.io/component: metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dex-operator
      app.kubernetes.io/component: metrics
  endpoints:
  - port: metrics
    interval: 30s