apiVersion: v1
kind: Service
metadata:
  name: dex-operator-metrics
  namespace: dex-operator
spec:
  selector:
    app.kubernetes.io/name: dex-operator
    app.kubernetes.io/component: metrics
  ports:
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080