apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: dex-operator
  name: dex-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dex-manager-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: dex-operator
