apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dex
  labels:
    app.kubernetes.io/component: provider
spec:
  secretName: dex-tls
  issuerRef:
    name: root-ca
    kind: ClusterIssuer
  dnsNames:
  - dex.default.svc.cluster.local
  - dex-api.default.svc.cluster.local