apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo
  labels:
    app.kubernetes.io/component: server
spec:
  secretName: demo-tls
  issuerRef:
    name: ca
  dnsNames:
  - dex-demo.default.svc.cluster.local
  - dex-demo-api.default.svc.cluster.local
