apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dex-operator-client
  labels:
    app.kubernetes.io/component: provider
spec:
  secretName: dex-operator-client-tls
  issuerRef:
    name: dex-api-ca
  commonName: Dex Operator API Client