apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-operator-client
  labels:
    app.kubernetes.io/component: provider
spec:
  secretName: demo-operator-client-tls
  issuerRef:
    name: demo-api-ca
  commonName: API Client
