apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dex-api-ca
spec:
  isCA: true
  secretName: dex-api-ca-tls
  issuerRef:
    name: root-ca
    kind: ClusterIssuer
  commonName: Dex API CA