kind: DexIdentityProvider
apiVersion: dex.gpu-ninja.com/v1alpha1
metadata:
  name: dex
  labels:
    app.kubernetes.io/component: provider
spec:
  image: dexidp/dex:v2.37.0
  clientCertificateSecretRef:
    name: dex-operator-client-tls
  issuer: http://auth.local.koopt.sh:8080
  oauth2:
    skipApprovalScreen: true
  storage:
    type: sqlite3
    sqlite3:
      file: /var/lib/dex/dex.db
  grpc:
    certificateSecretRef:
      name: dex-tls
    clientCASecretRef:
      name: dex-api-ca-tls
  web:
    certificateSecretRef:
      name: dex-tls
    allowedOrigins:
    - http://auth.local.koopt.sh:8080
    annotations:
      traefik.ingress.kubernetes.io/service.serversscheme: https
      traefik.ingress.kubernetes.io/service.serverstransport: default-dex@kubernetescrd
  ingress:
    enabled: true
    hosts:
    - host: auth.local.koopt.sh
      paths:
      - path: /
        pathType: Prefix
  metrics:
    enabled: true
  volumeMounts:
  - name: data
    mountPath: /var/lib/dex
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Mi