kind: DexIdentityProvider
apiVersion: dex.gpu-ninja.com/v1alpha1
metadata:
  name: demo
  labels:
    app.kubernetes.io/component: provider
spec:
  image: dexidp/dex:v2.37.0
  clientCertificateSecretRef:
    name: demo-operator-client-tls
  issuer: https://dex.example.com
  storage:
    type: sqlite3
    sqlite3:
      file: /var/lib/dex/dex.db
  web:
    certificateSecretRef:
      name: demo-tls
    allowedOrigins:
    - https://dex.example.com
  grpc:
    certificateSecretRef:
      name: demo-tls
    clientCASecretRef:
      name: demo-api-ca-tls
    reflection: true
  metrics:
    enabled: true
    interval: 30s
  connectors:
  - type: ldap
    name: LDAP
    id: ldap
    ldap:
      host: ldap.example.com:636
      caSecretRef:
        name: ca-tls
      bindUsername: cn=admin,dc=example,dc=com
      bindPasswordSecretRef:
        name: ldap-bind-password
      userSearch:
        baseDN: ou=users,dc=example,dc=com
        filter: (objectClass=person)
        username: uid
        idAttr: uid
        emailAttr: mail
        nameAttr: cn
        preferredUsernameAttr: uid
      groupSearch:
        baseDN: ou=groups,dc=example,dc=com
        filter: "(objectClass=groupOfNames)"
        nameAttr: cn
        userMatchers:
        - userAttr: uid
          groupAttr: member
  volumeMounts:
  - name: data
    mountPath: /var/lib/dex
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi