kind: DexOAuth2Client
apiVersion: dex.gpu-ninja.com/v1alpha1
metadata:
  name: demo
spec:
  identityProviderRef:
    name: dex
  secretName: demo-client-secret
  redirectURIs:
  - http://demo-client.local.koopt.sh:8081/oauth2/callback