apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  labels:
    app.kubernetes.io/component: provider
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca
  labels:
    app.kubernetes.io/component: provider
spec:
  isCA: true
  secretName: ca-tls
  issuerRef:
    name: selfsigned-issuer
  commonName: Root CA
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca
  labels:
    app.kubernetes.io/component: provider
spec:
  ca:
    secretName: ca-tls
