apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: dex
  labels:
    app.kubernetes.io/component: provider
spec:
  serverName: dex.default.svc.cluster.local
  rootCAsSecrets:
  - root-ca-tls